# Generated by Django 3.1.3 on 2020-11-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
